### ISSUE TITLE
Connect to DB via MysqlWorkbench

### ISSUE THREAD

**Issue by appsol** [tutumcloud/mysql#54]
Hi,

I'm using this container together with tutm/apache-php to quickly spin up dev sites. One issue would make it perfect and that is if I could connect MySQL Workbench to the db, so I can monitor the result of queries, etc.

Any idea how I would do this? The host is my Ubuntu 14.04 workstation.

Thanks

Stuart

**Comment by borjaburgos** [comment]
Not familiar with MySQL Workbench, but can't you just simply connect to the DB running inside the container by publishing the 3306 port?

**Comment by Tebro** [comment]
What @borjaburgos said, if you publish the MySQL port on the host you can connect with any MySQL tool, including workbench.
