### ISSUE TITLE
If the container is reloaded, mysqld is started twice

### ISSUE THREAD

**Issue by tonnydourado** [tutumcloud/mysql#55]
When stopping and starting again the container, it ends up with two `mysqld` processes running (which seems to cause the container to stop after a while). I managed to fix it (I think) changing this [line](https://github.com/tutumcloud/tutum-docker-mysql/blob/master/5.5/run.sh#L13) to the following:

````
 mysql -uroot -e "status" > /dev/null 2>&1 && /usr/bin/mysqld_safe > /dev/null 2>&1 &
````

**Comment by tifayuki** [comment]
Hi, I didn't encounter such a problem. From the code, it should not start mysql twice.
How did you run mysql? use volume? use importsql?

**Comment by tonnydourado** [comment]
I think I used run.sh as the container's command (I had to specify it because I use packer to generate the image, and it doesn't preserve the CMD from the images).

**Comment by tifayuki** [comment]
Your fix reads like:
If mysql isn't running, `mysql -uroot -e "status" > /dev/null 2>&1` will return non-zero value and `/usr/bin/mysqld_safe > /dev/null 2>&1 &` will be ignored. This means the startup function doesn't work.

**Comment by tonnydourado** [comment]
Hmm, I think I wrote it wrong. The first command should return a non-zero value if mysqld **IS** running, causing it to not be started again. There should be a negation there somewhere, or something like that. Guess I hadn't had my coffee the morning I posted that =/
