### ISSUE TITLE
"Installation of system tables failed" on Mac OS when mounting file volume with boot2docker 1.5

### ISSUE THREAD

**Issue by dbaltas** [tutumcloud/mysql#56]
I have trouble when mounting a volume om the mysql container

I am running boot2docker 1.5

When I run

    docker run -v $HOME/mysql-data:/var/lib/mysql tutum/mysql /bin/bash -c "/usr/bin/mysql_install_db"

i get this error 

*Installation of system tables failed!  Examine the logs in /var/lib/mysql for more information.*

Running the above command also creates an **empty** $HOME/mysql-data/mysql folder.

The tutum/mysql container runs smoothly when no mounting occurs.

I have successfully mounted a folder on the nginx demo container, which means that the boot2docker is setup correctly for mounting volumes.

**Comment by rajeev47billion** [comment]
I am having similar trouble with mysql 5.6 and still debugging.

For 5.5, I added the following in run.sh and it is working with mounted volume -

chmod 700 $VOLUME_HOME
# This changes uid to 1000 for mysql which is what is used by docker to mount host volume
usermod -u 1000 mysql
chown -R mysql:mysql $VOLUME_HOME
# Avoids could not find mysql.sock error
chown -R mysql:mysql /var/run/mysqld

**Comment by tifayuki** [comment]
There are various permission issues when you mount a volume using boot2docker to your host. Your nginx demo container works fine with volume could be the reason that it is a read-only data volume, and writing data to a volume is a different thing. 

In Dockerfile, we have defined volume `/var/lib/mysql`. This means that the data in `mysql` container is stored in the VM of boot2docker. You can mount that folder to you mac in VirtualBox settings. Alternatively you can put the volume in a volume container, if you want to reuse the volume.
