### ISSUE TITLE
Env var to specify database name when importing sql file

### ISSUE THREAD

**Issue by marcelpanse** [tutumcloud/mysql#63]
Currently when doing: 
`docker run --name mysql -e MYSQL_PASS="pass" -e ON_CREATE_DB="wordpress" -e STARTUP_SQL="/tmp/init.sql" -d marcelpanse/mysql:latest`

There is no way to specify the db name to import the sql to, resulting in:
`ERROR 1046 (3D000) at line 22: No database selected`

**Comment by Tebro** [comment]
I will look at it, should it be another boolean variable like IMPORT_TO_CREATED_DB?

**Comment by marcelpanse** [comment]
Since it should match with `STARTUP_SQL`, maybe `STARTUP_SQL_DB`?

**Comment by Tebro** [comment]
@marcelpanse but would that name not suggest that it expects a DB name? Instead of a boolean value of true to import to the $ON_CREATE_DB.

**Comment by marcelpanse** [comment]
yes, that was what i was thinking. But maybe you are right, since there won't be another DB anyway to import to. 

Don't you always want to import to the created db by default? (then you don't need a var)..

**Comment by Tebro** [comment]
Unsure if the best way to proceed is to assume what users want though, at least if we are able to leave it up to the users choice.

**Comment by modius** [comment]
I typically get around this by creating and "using" the relevant database as part of the import SQL:

```
CREATE DATABASE `mynewdatabase`;
USE `mynewdatabase`;
```

I'm not sure that additional ENV variables are all that helpful, given you can issue these commands directly within the SQL, and its only run the one time on container creation.

**Comment by Tebro** [comment]
With #65 being merged this issue can be closed.
