### ISSUE TITLE
Admin user denied with password on MySQL 5.6

### ISSUE THREAD

**Issue by TedAvery** [tutumcloud/mysql#67]
I am trying out the basic setup as outlined in the Usage section of the readme, but instead changing `docker build -t tutum/mysql 5.5/` to `docker build -t tutum/mysql 5.6/`.

I then run `docker logs` to see the password generated for my `admin` user.

I separately run `docker exec -it <container_id> /bin/bash` in another window, then try using the login that the logs displayed (e.g. `mysql -uadmin -p47nnf4FweaKu`), and am rejected with an access denied message.

Strangely, even if I go in and try to manually override the admin user's password by first entering `mysql` without `-u` or `-p` attached, then run `SET PASSWORD FOR 'admin'@'%' = PASSWORD('abc123');`, then test logging in again (e.g. `mysql -uadmin -ptesting123`), access is still denied.

Everything works fine if I leave the first build command at 5.5.

**Comment by trompx** [comment]
Hello @TedAvery,
Same here, I get ```ERROR 1045 (28000): Access denied for user 'admin'@'localhost' (using password: YES)```.
To be able to connect, did you add the -hhost -Pport as suggested? When I enter -h192.168.33.101 (ip of the docker host) -P3306 , it works.
But when trying to connect from a web container, the only way I manage to connect is to use the replica:replica user, trying to connect with admin / admin_password result in a ```mysqli_connect(): (HY000/1045): Access denied for user 'admin'@'192.168.33.101' (using password: YES)```

**Comment by EwanValentine** [comment]
I'm also getting this

**Comment by EwanValentine** [comment]
I was using user root instead of admin, my bad.
