### ISSUE TITLE
ERROR 1130 (HY000): Host 'xxx.xx.xxx.xxx' is not allowed to connect to this MySQL

### ISSUE THREAD

**Issue by oerk** [tutumcloud/mysql#74]
Mounting the database file volume  find  a issues
docker run -d -v /path/in/host:/var/lib/mysql tutum/mysql /bin/bash -c "/usr/bin/mysql_install_db"
and
docker run -d -p 3306:3306 -v /path/in/host:/var/lib/mysql tutum/mysql
the two step 
after set up connect to mysql will   ERROR 1130 (HY000): Host 'xxx.xx.xxx.xxx' is not allowed to connect to this MySQL ,because the use hadn't create

we must add a step,like this
docker run -d -v /path/in/host:/var/lib/mysql tutum/mysql /bin/bash -c "/usr/bin/mysql_install_db"

touch /path/in/host/.EMPTY_DB   # ADD THIS WILL FIX 

docker run -d -p 3306:3306 -v /path/in/host:/var/lib/mysql tutum/mysql

**Comment by tifayuki** [comment]
Hi @oerk 

We recently changed the way to initialize an empty volume to increase the start up of MySQL. 

You don't need to run `docker run -d -v /path/in/host:/var/lib/mysql tutum/mysql /bin/bash -c "/usr/bin/mysql_install_db"` any more.

you can directly use `docker run -d -p 3306:3306 -v /path/in/host:/var/lib/mysql tutum/mysql`, and `run.sh` will do all the initialization of the database.

The README is out dated, I will update it soon.

**Comment by drasamsetti** [comment]
I have similar issue, my env is Boot2docker, when i run command
docker run -d -p 3306:3306 -v //c/Users/db:/tmp -e MYSQL_PASS="pass" -e ON_CREATE_DB= -e STARTUP_SQL="/tmp/<.sql file>" tutum/mysql(5.6)

i have placed my import sql file on /c/Users/db folder on docker host (boot2docker)
error:
$ docker logs 9d8752169a36
=> Using an existing volume of MySQL
=> Starting MySQL ...
=> Waiting for confirmation of MySQL service startup, trying 0/60 ...
=> Waiting for confirmation of MySQL service startup, trying 1/60 ...
=> Waiting for confirmation of MySQL service startup, trying 2/60 ...
=> Waiting for confirmation of MySQL service startup, trying 3/60 ...
=> Waiting for confirmation of MySQL service startup, trying 4/60 ...

when logged into contianer..and running mysql..
root@9d87521:/# mysql
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

pls explain how "-v" works on boot2docker when one wants to import an sql file once DB is crated.

**Comment by tifayuki** [comment]
@drasamsetti 

When you mount something from your host using boot2docker,  the `tutum/mysql` container doesn't have permission to write to that folder.

Using ` -v //c/Users/db:/tmp`, mysql need to create some files in `/tmp`, which is your `//c/Users/db`. As mysql doesn't have the permission to create tmp files, it failed to start.

To fix this, you can mount you sql script to other folders, e.g. ` -v //c/Users/db:/script` and set `STARTUP_SQL="/script/<.sql file>" `
