### ISSUE TITLE
ENV var for lower_case_table_names

### ISSUE THREAD

**Issue by modius** [tutumcloud/mysql#75]
Seeing as developers in the Docker world are frequently moving between operating systems, this might be useful to others.

Suggest an ENV variable option; for example:
LOWER_CASE_TABLE_NAMES=1

How table case sensitivity works:
http://dev.mysql.com/doc/refman/5.0/en/identifier-case-sensitivity.html

The options for adjusting the behaviour:
http://dev.mysql.com/doc/refman/5.0/en/server-system-variables.html#sysvar_lower_case_table_names

**Comment by tifayuki** [comment]
added `EXTRA_OPTS`, so that you can do `-e EXTRA_OPTS='--lower_case_table_name=1'

**Comment by modius** [comment]
Wonderful, thanks :)  Will give it a go.
