### ISSUE TITLE
Generated password is not exposed to linked containers.

### ISSUE THREAD

**Issue by Tebro** [tutumcloud/mysql#77]
When linking a container to the mysql container the $MYSQL_ENV_MYSQL_PASS env variable is `**Random**` if one did not choose a password. Is there a way to update this variable so that linked services be configured more easily?

**Comment by fermayo** [comment]
No, the environment variable cannot be updated after the container is launched. The only way to make it work is to set a password when launching MySQL.

**Comment by Tebro** [comment]
Okay, oh well.
